// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Range struct {
	StartID     int64              `json:"start_id"`
	EndID       int64              `json:"end_id"`
	AllocatedAt pgtype.Timestamptz `json:"allocated_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	RangeID     uuid.UUID          `json:"range_id"`
	Region      pgtype.Text        `json:"region"`
	ServiceID   string             `json:"service_id"`
	Status      string             `json:"status"`
}
